FROM node:16-alpine As buid
WORKDIR /usr/src/app
COPY . .
RUN npm install 
RUN npm run build


### Production Image ###
FROM node:16-alpine As production
WORKDIR /usr/src/app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ARG PORT=8888
ENV PORT=${PORT}

COPY --from=buid /usr/src/app/package.json ./package.json
COPY --from=buid /usr/src/app/node_modules ./node_modules
COPY --from=buid /usr/src/app/dist ./dist

EXPOSE ${PORT}

CMD [ "node", "dist/main.js" ]
