FROM public.ecr.aws/lambda/nodejs:16 As development
WORKDIR /usr/src/app
COPY . .
RUN npm install 
RUN npm run build

### Production Image ###
FROM public.ecr.aws/lambda/nodejs:16 As production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
COPY --from=development /usr/src/app/package.json ./package.json
COPY --from=development /usr/src/app/node_modules ./node_modules
COPY --from=development /usr/src/app/dist ./dist

CMD ["dist/lambda.handler"]
